name: macOS CPU Info (Native + Rosetta)

on: [push]

jobs:
  cpu-info:
    runs-on: macos-latest
    steps:
      - name: Install Rosetta (if needed)
        run: |
          echo "=== Checking System Architecture ==="
          uname -m
          sysctl -n machdep.cpu.brand_string
          sysctl -a | grep machdep.cpu

          if [[ "$(uname -m)" == "arm64" ]]; then
            echo "Apple Silicon detected, attempting to install Rosetta..."
            sudo softwareupdate --install-rosetta --agree-to-license
          else
            echo "Running on Intel, no Rosetta needed."
          fi

      - name: Verify Rosetta Installation
        run: |
          echo "=== Checking Rosetta Binary ==="
          if [[ -f "/usr/libexec/rosetta" ]]; then
            echo "Rosetta binary exists!"
          else
            echo "Rosetta binary NOT found!"
          fi

          echo "=== Checking Running Processes ==="
          ps aux | grep oahd | grep -v grep || echo "Rosetta process (oahd) is NOT running!"

          echo "=== Checking Rosetta Translation Capabilities ==="
          arch -x86_64 true && echo "Rosetta is working!" || echo "Rosetta is NOT working!"

      - name: Print CPU Info (Native + Rosetta)
        run: |
          echo "=== Native CPU Info ==="
          arch
          uname -a
          sysctl -a | grep machdep.cpu

          if arch -x86_64 true 2>/dev/null; then
            echo -e "\n=== Rosetta (x86_64) CPU Info ==="
            arch -x86_64 arch
            arch -x86_64 uname -a
            arch -x86_64 sysctl -a | grep machdep.cpu
          else
            echo "Rosetta is not available or not functioning correctly."
          fi
