name: macOS Rosetta CPU Info (With x86 Execution Test)

on: [push]

jobs:
  cpu-info:
    runs-on: macos-latest
    steps:
      - name: Install Rosetta (if needed)
        run: |
          if [[ "$(uname -m)" == "arm64" ]]; then
            echo "Apple Silicon detected, attempting to install Rosetta..."
            sudo softwareupdate --install-rosetta --agree-to-license
          else
            echo "Running on Intel, no Rosetta needed."
          fi

      - name: Compile x86-64 Binary
        run: |
          echo "=== Compiling x86-64 Test Program ==="
          cat <<EOF > hello.c
          #include <stdio.h>
          int main() {
              printf("Hello from x86-64!\n");
              return 0;
          }
          EOF
          
          echo "=== Compiling Using x86-64 Mode ==="
          clang -target x86_64-apple-macos -o hello_x86 hello.c || echo "Failed to compile x86-64 binary!"

          echo "=== Checking Binary Architecture ==="
          file hello_x86 || echo "x86-64 binary missing!"

      - name: Run x86-64 Binary Using Rosetta
        run: |
          echo "=== Attempting to Execute x86-64 Binary ==="
          if arch -x86_64 ./hello_x86; then
            echo "SUCCESS: x86-64 execution works under Rosetta!"
          else
            echo "FAILED: x86-64 execution does NOT work!"
          fi
