name: Verify sysctl Behavior in GitHub Actions

on: [push]

jobs:
  sysctl-test:
    runs-on: macos-latest
    steps:
      - name: Install Rosetta (if needed)
        run: |
          if [[ "$(uname -m)" == "arm64" ]]; then
            echo "Apple Silicon detected, attempting to install Rosetta..."
            sudo softwareupdate --install-rosetta --agree-to-license
          else
            echo "Running on Intel, no Rosetta needed."
          fi

      - name: Run sysctl on Native ARM64
        run: |
          echo "=== Running sysctl -a (ARM64) ==="
          sysctl -a > native_sysctl.txt || echo "sysctl failed!"
          echo "=== Running sysctl -n sysctl.proc_translated (ARM64) ==="
          sysctl -n sysctl.proc_translated || echo "sysctl.proc_translated not available!"

      - name: Compile and Run x86-64 Binary
        run: |
          echo "=== Compiling x86-64 Test Program ==="
          cat <<EOF > hello.c
          #include <stdio.h>
          int main() {
              printf("Hello from x86-64!\n");
              return 0;
          }
          EOF
          
          echo "=== Compiling Using x86-64 Mode ==="
          clang -target x86_64-apple-macos -o hello_x86 hello.c || echo "Failed to compile x86-64 binary!"
          
          echo "=== Checking Binary Architecture ==="
          file hello_x86 || echo "x86-64 binary missing!"

          echo "=== Running x86-64 Binary Using Rosetta ==="
          arch -x86_64 ./hello_x86 || echo "Failed to execute x86-64 binary!"

      - name: Run sysctl on Rosetta x86-64
        run: |
          echo "=== Running sysctl -a (Rosetta x86-64) ==="
          arch -x86_64 sysctl -a > rosetta_sysctl.txt || echo "sysctl failed in Rosetta!"
          echo "=== Running sysctl -n sysctl.proc_translated (Rosetta x86-64) ==="
          arch -x86_64 sysctl -n sysctl.proc_translated || echo "sysctl.proc_translated not available under Rosetta!"

      - name: Compare sysctl Outputs
        run: |
          echo "=== Comparing sysctl outputs (ARM64 vs Rosetta x86-64) ==="
          diff -u native_sysctl.txt rosetta_sysctl.txt || echo "Differences detected!"
